// <auto-generated />
using System;
using DallyWorkReoprt.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DallyWorkReoprt.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402050136_ChangeWorkLogToInt")]
    partial class ChangeWorkLogToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ClientMaster", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientShortCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.HasKey("ClientId");

                    b.HasIndex(new[] { "CompanyId" }, "IX_ClientMaster_CompanyID");

                    b.ToTable("ClientMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.CompanyMaster", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("Guids")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsEmailVerified")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsMobileNoVerified")
                        .HasColumnType("tinyint");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PreferredSubDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("StateID");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CompanyId");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("CompanyId"), 80);

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("CompanyMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.CountryMaster", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CurrencySymbole")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("Guids")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CountryId");

                    b.ToTable("CountryMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmailRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__EmailRec__3214EC07E619AE4F");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmailRecipients");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmailSetting", b =>
                {
                    b.Property<int>("EmailSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailSettingsId"));

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmailSettingsId")
                        .HasName("PK__EmailSet__24746D17D68426E7");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmployeeMaster", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Doj")
                        .HasColumnType("date")
                        .HasColumnName("DOJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("EmployeeCode")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(302)
                        .HasColumnType("nvarchar(302)")
                        .HasComputedColumnSql("(concat_ws(' ',nullif(ltrim(rtrim([FirstName])),''),nullif(ltrim(rtrim([MiddleName])),''),nullif(ltrim(rtrim([LastName])),'')))", false);

                    b.Property<string>("EmployeePhotoFile")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("GenderID");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte>("IsAllowLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Passwords")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("RoleMasterId")
                        .HasColumnType("int")
                        .HasColumnName("RoleMasterID");

                    b.Property<byte>("SignInAttempt")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Tenant")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId")
                        .HasName("PK_StaffMaster");

                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("EmployeeId"), 80);

                    b.HasIndex("GenderId");

                    b.HasIndex("RoleMasterId");

                    b.ToTable("EmployeeMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Controller")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ErrorLog__3214EC0788BF7A23");

                    b.ToTable("ErrorLog");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LookupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("PK_Table_1");

                    b.HasIndex("TypeId");

                    b.ToTable("Lookup");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.LookupType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("LookupType");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.MailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CreatedByID");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FooterHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("HeaderHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ModifiedBYID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SubjectFormat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TableConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MailTemplates");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ModuleMaster", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ParentModuleID");

                    b.HasKey("ModuleId");

                    b.HasIndex("ParentModuleId");

                    b.HasIndex(new[] { "CompanyId" }, "IX_ModuleMaster_CompanyID");

                    b.ToTable("ModuleMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ProjectMaster", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProjectColor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectId");

                    b.HasIndex(new[] { "CompanyId" }, "IX_ProjectMaster_CompanyID");

                    b.ToTable("ProjectMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.RoleMaster", b =>
                {
                    b.Property<int>("RoleMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleMasterId"));

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<string>("Descriptions")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("Guids")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleTypeId")
                        .HasColumnType("int");

                    b.HasKey("RoleMasterId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleTypeId");

                    b.ToTable("RoleMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.RoleMasterSoftwareModule", b =>
                {
                    b.Property<int>("RoleMasterSoftwareModulesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleMasterSoftwareModulesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleMasterSoftwareModulesId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<bool?>("Add")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CreatedByID");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<bool?>("Edit")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleMasterId")
                        .HasColumnType("int")
                        .HasColumnName("RoleMasterID");

                    b.Property<int>("SoftwareModulesMasterId")
                        .HasColumnType("int")
                        .HasColumnName("SoftwareModulesMasterID");

                    b.Property<bool?>("View")
                        .HasColumnType("bit");

                    b.HasKey("RoleMasterSoftwareModulesId");

                    b.HasIndex("RoleMasterId");

                    b.HasIndex("SoftwareModulesMasterId");

                    b.ToTable("RoleMasterSoftwareModules");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.SoftwareModulesMaster", b =>
                {
                    b.Property<int>("SoftwareModulesMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SoftwareModulesMasterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareModulesMasterId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("ControllersName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CrDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("DisplayLevel")
                        .HasColumnType("tinyint");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExternalUri")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("ExternalURI");

                    b.Property<string>("FullUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("FullURL");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool?>("HasCreate")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("ModulesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareModulesMasterId")
                        .HasName("PK_ModulesMaster");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("SoftwareModulesMasterId"), false);
                    SqlServerKeyBuilderExtensions.HasFillFactor(b.HasKey("SoftwareModulesMasterId"), 80);

                    b.HasIndex("ParentId");

                    b.ToTable("SoftwareModulesMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.StateMaster", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("StateID");

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<Guid>("Guids")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StateId");

                    b.ToTable("StateMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.StatusMaster", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedByID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("StatusColor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StatusId");

                    b.HasIndex(new[] { "CompanyId" }, "IX_StatusMaster_CompanyID");

                    b.ToTable("StatusMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CreatedByID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ModifiedBYID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SrNo")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WorkReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkReportId");

                    b.ToTable("WorkEntries");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkLog", b =>
                {
                    b.Property<int>("WorkLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkLogId"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("InputTime")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBYID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OtherEmployeeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDuration")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkLogId");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkLogTask", b =>
                {
                    b.Property<int>("WorkLogTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkLogTaskId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedByID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("WorkLogId")
                        .HasColumnType("int");

                    b.HasKey("WorkLogTaskId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkLogId");

                    b.ToTable("WorkLogTasks");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CreatedByID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ModifiedBYID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkReports");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkTimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CreatedByID");

                    b.Property<Guid>("Guids")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("InTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Is30MinBreak")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ModifiedBYID");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("OutTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("WorkEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkEntryId");

                    b.ToTable("WorkTimeLogs");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ClientMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.CompanyMaster", "Company")
                        .WithMany("ClientMasters")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_ClientMaster_CompanyMaster");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.CompanyMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.CountryMaster", "Company")
                        .WithMany("CompanyMasters")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("FK_CompanyMaster_CountryMaster");

                    b.HasOne("DallyWorkReoprt.DAL.Models.StateMaster", "State")
                        .WithMany("CompanyMasters")
                        .HasForeignKey("StateId")
                        .HasConstraintName("FK_CompanyMaster_StateMaster");

                    b.Navigation("Company");

                    b.Navigation("State");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmailRecipient", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.EmployeeMaster", "Employee")
                        .WithMany("EmailRecipients")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_EmailRecipients_EmployeeMaster");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmailSetting", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.EmployeeMaster", "Employee")
                        .WithMany("EmailSettings")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_EmailSettings_EmployeeMaster");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmployeeMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.Lookup", "Gender")
                        .WithMany("EmployeeMasters")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("FK_EmployeeMaster_Lookup");

                    b.HasOne("DallyWorkReoprt.DAL.Models.RoleMaster", "RoleMaster")
                        .WithMany("EmployeeMasters")
                        .HasForeignKey("RoleMasterId")
                        .HasConstraintName("FK_EmployeeMaster_RoleMaster");

                    b.Navigation("Gender");

                    b.Navigation("RoleMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.Lookup", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.LookupType", "Type")
                        .WithMany("Lookups")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Lookup_LookupType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ModuleMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.CompanyMaster", "Company")
                        .WithMany("ModuleMasters")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleMaster_CompanyMaster");

                    b.HasOne("DallyWorkReoprt.DAL.Models.ModuleMaster", "ParentModule")
                        .WithMany("InverseParentModule")
                        .HasForeignKey("ParentModuleId")
                        .HasConstraintName("FK_ModuleMaster_ParentModule");

                    b.Navigation("Company");

                    b.Navigation("ParentModule");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ProjectMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.CompanyMaster", "Company")
                        .WithMany("ProjectMasters")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectMaster_CompanyMaster");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.RoleMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.CompanyMaster", "Company")
                        .WithMany("RoleMasters")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_RoleMaster_InstituteMaster");

                    b.HasOne("DallyWorkReoprt.DAL.Models.Lookup", "RoleType")
                        .WithMany("RoleMasters")
                        .HasForeignKey("RoleTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_RoleMaster_Lookup");

                    b.Navigation("Company");

                    b.Navigation("RoleType");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.RoleMasterSoftwareModule", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.RoleMaster", "RoleMaster")
                        .WithMany("RoleMasterSoftwareModules")
                        .HasForeignKey("RoleMasterId")
                        .IsRequired()
                        .HasConstraintName("FK_RoleMasterSoftwareModules_RoleMaster");

                    b.HasOne("DallyWorkReoprt.DAL.Models.SoftwareModulesMaster", "SoftwareModulesMaster")
                        .WithMany("RoleMasterSoftwareModules")
                        .HasForeignKey("SoftwareModulesMasterId")
                        .IsRequired()
                        .HasConstraintName("FK_RoleMasterSoftwareModules_SoftwareModulesMaster");

                    b.Navigation("RoleMaster");

                    b.Navigation("SoftwareModulesMaster");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.SoftwareModulesMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.SoftwareModulesMaster", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_SoftwareModulesMaster_SoftwareModulesMaster");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.StatusMaster", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.CompanyMaster", "Company")
                        .WithMany("StatusMasters")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_StatusMaster_CompanyMaster");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkEntry", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.ModuleMaster", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.HasOne("DallyWorkReoprt.DAL.Models.ProjectMaster", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DallyWorkReoprt.DAL.Models.StatusMaster", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DallyWorkReoprt.DAL.Models.WorkReport", "WorkReport")
                        .WithMany("WorkEntries")
                        .HasForeignKey("WorkReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Project");

                    b.Navigation("Status");

                    b.Navigation("WorkReport");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkLog", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.ClientMaster", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DallyWorkReoprt.DAL.Models.EmployeeMaster", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DallyWorkReoprt.DAL.Models.ProjectMaster", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DallyWorkReoprt.DAL.Models.StatusMaster", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkLogTask", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.StatusMaster", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DallyWorkReoprt.DAL.Models.WorkLog", "WorkLog")
                        .WithMany("WorkLogTasks")
                        .HasForeignKey("WorkLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkReport", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.EmployeeMaster", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkTimeLog", b =>
                {
                    b.HasOne("DallyWorkReoprt.DAL.Models.WorkEntry", "WorkEntry")
                        .WithMany("TimeLogs")
                        .HasForeignKey("WorkEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkEntry");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.CompanyMaster", b =>
                {
                    b.Navigation("ClientMasters");

                    b.Navigation("ModuleMasters");

                    b.Navigation("ProjectMasters");

                    b.Navigation("RoleMasters");

                    b.Navigation("StatusMasters");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.CountryMaster", b =>
                {
                    b.Navigation("CompanyMasters");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.EmployeeMaster", b =>
                {
                    b.Navigation("EmailRecipients");

                    b.Navigation("EmailSettings");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.Lookup", b =>
                {
                    b.Navigation("EmployeeMasters");

                    b.Navigation("RoleMasters");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.LookupType", b =>
                {
                    b.Navigation("Lookups");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.ModuleMaster", b =>
                {
                    b.Navigation("InverseParentModule");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.RoleMaster", b =>
                {
                    b.Navigation("EmployeeMasters");

                    b.Navigation("RoleMasterSoftwareModules");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.SoftwareModulesMaster", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("RoleMasterSoftwareModules");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.StateMaster", b =>
                {
                    b.Navigation("CompanyMasters");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkEntry", b =>
                {
                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkLog", b =>
                {
                    b.Navigation("WorkLogTasks");
                });

            modelBuilder.Entity("DallyWorkReoprt.DAL.Models.WorkReport", b =>
                {
                    b.Navigation("WorkEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
